/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gym.management.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Nomi's
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        btnManageMembers = new javax.swing.JButton();
        btnManageStaff = new javax.swing.JButton();
        btnManageFinance = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnManageMemberships = new javax.swing.JButton();
        btnPhysicalStats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Dashboard - Gym Management System");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("ADMIN DASHBOARD");

        welcomeLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(204, 204, 204));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome, Administrator!");

        btnManageMembers.setBackground(new java.awt.Color(52, 152, 219));
        btnManageMembers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageMembers.setText("MANAGE MEMBERS");
        btnManageMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMembersActionPerformed(evt);
            }
        });

        btnManageStaff.setBackground(new java.awt.Color(46, 204, 113));
        btnManageStaff.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageStaff.setText("MANAGE STAFF");
        btnManageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStaffActionPerformed(evt);
            }
        });

        btnManageFinance.setBackground(new java.awt.Color(155, 89, 182));
        btnManageFinance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageFinance.setText("MANAGE FINANCE");
        btnManageFinance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFinanceActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(231, 76, 60));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnManageMemberships.setBackground(new java.awt.Color(241, 196, 15));
        btnManageMemberships.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageMemberships.setText("MANAGE MEMBERSHIPS");
        btnManageMemberships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMembershipsActionPerformed(evt);
            }
        });

        btnPhysicalStats.setBackground(new java.awt.Color(26, 188, 156));
        btnPhysicalStats.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPhysicalStats.setText("VIEW PHYSICAL STATS");
        btnPhysicalStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhysicalStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageMemberships)
                            .addComponent(btnManageFinance, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPhysicalStats, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(72, 72, 72))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addGap(183, 183, 183))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLabel)
                .addGap(26, 26, 26)
                .addComponent(welcomeLabel)
                .addGap(47, 47, 47)
                .addComponent(btnManageMembers)
                .addGap(22, 22, 22)
                .addComponent(btnManageMemberships)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnManageStaff)
                .addGap(25, 25, 25)
                .addComponent(btnManageFinance)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPhysicalStats)
                    .addComponent(btnLogout))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMembersActionPerformed
        MemberManagementFrame memberFrame = new MemberManagementFrame();
    memberFrame.setVisible(true);
    }//GEN-LAST:event_btnManageMembersActionPerformed

    private void btnManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStaffActionPerformed
         StaffManagementFrame staffFrame = new StaffManagementFrame();
    staffFrame.setVisible(true);
    }//GEN-LAST:event_btnManageStaffActionPerformed

    private void btnManageFinanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFinanceActionPerformed
         FinanceFrame financeFrame = new FinanceFrame();
    financeFrame.setVisible(true);
    }//GEN-LAST:event_btnManageFinanceActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
         int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Logout Confirmation",
        JOptionPane.YES_NO_OPTION
    );
    
    if (choice == JOptionPane.YES_OPTION) {
        this.dispose();
        LoginFrame login = new LoginFrame();
        login.setVisible(true);
    }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageMembershipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMembershipsActionPerformed
       MembershipManagementFrame membershipFrame = new MembershipManagementFrame();
        membershipFrame.setVisible(true);
    }//GEN-LAST:event_btnManageMembershipsActionPerformed

    private void btnPhysicalStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhysicalStatsActionPerformed
         PhysicalStatsFrame physicalFrame = new PhysicalStatsFrame();
         physicalFrame.setVisible(true);
    }//GEN-LAST:event_btnPhysicalStatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageFinance;
    private javax.swing.JButton btnManageMembers;
    private javax.swing.JButton btnManageMemberships;
    private javax.swing.JButton btnManageStaff;
    private javax.swing.JButton btnPhysicalStats;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
