/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gym.management.gui;

import com.gym.management.models.Payment;
import com.gym.management.models.Staff;
import com.gym.management.services.FinanceService;
import com.gym.management.services.StaffService;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author Nomi's
 */
public class FinanceFrame extends javax.swing.JFrame {
    
    private FinanceService financeService;
    private DefaultTableModel tableModel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinanceFrame.class.getName());

    /**
     * Creates new form FinanceFrame
     */
    public FinanceFrame() {
        initComponents();
        financeService = new FinanceService();
        tableModel = (DefaultTableModel) tblPayments.getModel();
        loadPayments();
        updateTotals();
    }
    
    private void loadPayments() {
    tableModel.setRowCount(0);
    
    ArrayList<Payment> payments = financeService.getPaymentDetails();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    for (Payment payment : payments) {
        Object[] row = {
            payment.getPaymentId(),
            payment.getPaymentType(),
            payment.getAmount(), 
            dateFormat.format(payment.getDate()),
            payment.getDescription()
        };
        tableModel.addRow(row);
    }
}

private void updateTotals() {
    double revenue = financeService.getTotalRevenue();
    double expenses = financeService.getTotalOutcome();
    
    lblTotalRevenue.setText("Total Revenue: $" + String.format("%.2f", revenue));
    lblTotalExpenses.setText("Total Expenses: $" + String.format("%.2f", expenses));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRecordPayment = new javax.swing.JButton();
        lblTotalRevenue = new javax.swing.JLabel();
        lblTotalExpenses = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayments = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnProcessSalary = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnViewReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finance Management");

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        btnRecordPayment.setBackground(new java.awt.Color(204, 204, 204));
        btnRecordPayment.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnRecordPayment.setForeground(new java.awt.Color(0, 0, 0));
        btnRecordPayment.setText("Record Payment");
        btnRecordPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordPaymentActionPerformed(evt);
            }
        });

        lblTotalRevenue.setBackground(new java.awt.Color(46, 204, 113));
        lblTotalRevenue.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblTotalRevenue.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalRevenue.setText("Total Revenue: $0.00");

        lblTotalExpenses.setBackground(new java.awt.Color(231, 76, 60));
        lblTotalExpenses.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblTotalExpenses.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalExpenses.setText("Total Expenses: $0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnRecordPayment)
                .addGap(116, 116, 116)
                .addComponent(lblTotalRevenue)
                .addGap(122, 122, 122)
                .addComponent(lblTotalExpenses)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRecordPayment)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotalRevenue)
                        .addComponent(lblTotalExpenses)))
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblPayments.setAutoCreateRowSorter(true);
        tblPayments.setBackground(new java.awt.Color(204, 204, 204));
        tblPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Type", "Amount", "Date", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPayments.setRowHeight(25);
        tblPayments.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblPayments);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnProcessSalary.setBackground(new java.awt.Color(204, 204, 255));
        btnProcessSalary.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnProcessSalary.setForeground(new java.awt.Color(0, 0, 0));
        btnProcessSalary.setText("Process Salary");
        btnProcessSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessSalaryActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(185, 110, 118));
        btnRefresh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnViewReport.setBackground(new java.awt.Color(52, 152, 219));
        btnViewReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewReport.setText("View Report");
        btnViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnProcessSalary)
                .addGap(114, 114, 114)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(btnViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcessSalary)
                    .addComponent(btnRefresh)
                    .addComponent(btnViewReport))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecordPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordPaymentActionPerformed
        JTextField idField = new JTextField("PAY" + System.currentTimeMillis());
    idField.setEditable(false);
    
    String[] types = {"MEMBERSHIP_FEE", "SALARY", "OTHER"};
    JComboBox<String> typeCombo = new JComboBox<>(types);
    
    JTextField amountField = new JTextField();
    JTextField descField = new JTextField();
    JTextField refField = new JTextField();
    
    Object[] message = {
        "Payment ID:", idField,
        "Type:", typeCombo,
        "Amount:", amountField,
        "Description:", descField,
        "Reference ID:", refField
    };
    
    int option = JOptionPane.showConfirmDialog(
        this, 
        message, 
        "Record Payment", 
        JOptionPane.OK_CANCEL_OPTION
    );
    
    if (option == JOptionPane.OK_OPTION) {
        try {
            Payment payment = new Payment();
            payment.setPaymentId(idField.getText());
            payment.setPaymentType((String) typeCombo.getSelectedItem());
            payment.setAmount(Double.parseDouble(amountField.getText()));
            payment.setDate(new Date());
            payment.setDescription(descField.getText());
            payment.setReferenceId(refField.getText());
            
            financeService.recordPayment(payment);
            loadPayments();
            updateTotals();
            
            JOptionPane.showMessageDialog(this, "Payment recorded successfully!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid amount format!");
        }
    }
    }//GEN-LAST:event_btnRecordPaymentActionPerformed

    private void btnProcessSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessSalaryActionPerformed
        // Get all staff
    StaffService staffService = new StaffService();
    ArrayList<Staff> staffList = staffService.getStaffDetails();
    
    if (staffList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No staff found!");
        return;
    }
    
    // Create staff dropdown
    String[] staffNames = new String[staffList.size()];
    for (int i = 0; i < staffList.size(); i++) {
        staffNames[i] = staffList.get(i).getStaffId() + " - " + staffList.get(i).getName();
    }
    
    JComboBox<String> staffCombo = new JComboBox<>(staffNames);
    JTextField amountField = new JTextField();
    
    Object[] message = {
        "Select Staff:", staffCombo,
        "Salary Amount:", amountField
    };
    
    int option = JOptionPane.showConfirmDialog(
        this, 
        message, 
        "Process Salary", 
        JOptionPane.OK_CANCEL_OPTION
    );
    
    if (option == JOptionPane.OK_OPTION) {
        try {
            int selectedIndex = staffCombo.getSelectedIndex();
            Staff selectedStaff = staffList.get(selectedIndex);
            double amount = Double.parseDouble(amountField.getText());
            
            financeService.processSalary(selectedStaff, amount);
            loadPayments();
            updateTotals();
            
            JOptionPane.showMessageDialog(this, "Salary processed successfully!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid amount format!");
        }
    }
    }//GEN-LAST:event_btnProcessSalaryActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
         loadPayments();
         updateTotals();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
        double revenue = financeService.getTotalRevenue();
    double expenses = financeService.getTotalOutcome();
    double netProfit = revenue - expenses;
    
    String report = "=== FINANCIAL REPORT ===\n\n";
    report += "Total Revenue: $" + String.format("%.2f", revenue) + "\n";
    report += "Total Expenses: $" + String.format("%.2f", expenses) + "\n";
    report += "─────────────────────────\n";
    report += "Net Profit: $" + String.format("%.2f", netProfit) + "\n\n";
    
    if (netProfit > 0) {
        report += "Status: ✓ PROFIT";
    } else if (netProfit < 0) {
        report += "Status: ✗ LOSS";
    } else {
        report += "Status: = BREAK EVEN";
    }
    
    JOptionPane.showMessageDialog(
        this, 
        report, 
        "Financial Report", 
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnViewReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FinanceFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessSalary;
    private javax.swing.JButton btnRecordPayment;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalExpenses;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JTable tblPayments;
    // End of variables declaration//GEN-END:variables
}
