/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gym.management.gui;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;

/**
 *
 * @author Nomi's
 */
public class MembershipManagementFrame extends javax.swing.JFrame {
    
    private DefaultTableModel tableModel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MembershipManagementFrame.class.getName());

    /**
     * Creates new form MembershipManagementFrame
     */
    public MembershipManagementFrame() {
        initComponents();
        setupTable();
        loadMembershipPlans();
    }
    
    private void setupTable() {
    tableModel = (DefaultTableModel) tblMemberships.getModel();
}

private void loadMembershipPlans() {
    tableModel.setRowCount(0);
    
    // These are now all correctly handled as Strings
    tableModel.addRow(new Object[]{"M001", "Monthly", "$100.00", "30 days", "Active"});
    tableModel.addRow(new Object[]{"M002", "Quarterly", "$280.00", "3 months", "Active"});
    tableModel.addRow(new Object[]{"M003", "Semi-Annual", "$550.00", "6 months", "Active"});
    tableModel.addRow(new Object[]{"M004", "Annual", "$1200.00", "1 year", "Active"});
    tableModel.addRow(new Object[]{"M005", "Premium Annual", "$1800.00", "1 year", "Active"});
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMemberships = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Membership Management ");
        setSize(new java.awt.Dimension(900, 550));

        jPanel1.setBackground(new java.awt.Color(241, 196, 15));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("Membership Plans Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(titleLabel)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titleLabel)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblMemberships.setAutoCreateRowSorter(true);
        tblMemberships.setBackground(new java.awt.Color(204, 204, 204));
        tblMemberships.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Membership ID", "Type", "Fee", "Duration", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMemberships.setRowHeight(25);
        tblMemberships.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblMemberships);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setBackground(new java.awt.Color(46, 204, 113));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Add Plan");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(241, 196, 15));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Edit Plan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(231, 76, 60));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Delete Plan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(149, 165, 166));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addGap(113, 113, 113)
                .addComponent(jButton2)
                .addGap(123, 123, 123)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTextField idField = new JTextField("MEM" + System.currentTimeMillis());
    idField.setEditable(false);
    
    String[] types = {"Monthly", "Quarterly", "Semi-Annual", "Annual", "Premium Annual"};
    JComboBox<String> typeCombo = new JComboBox<>(types);
    
    JTextField feeField = new JTextField();
    
    Object[] message = {
        "Membership ID:", idField,
        "Membership Type:", typeCombo,
        "Fee ($):", feeField
    };
    
    int option = JOptionPane.showConfirmDialog(
        this, 
        message, 
        "Add Membership Plan", 
        JOptionPane.OK_CANCEL_OPTION
    );
    
    if (option == JOptionPane.OK_OPTION) {
        try {
            String type = (String) typeCombo.getSelectedItem();
            String duration = "";
            
            switch (type) {
                case "Monthly":
                    duration = "30 days";
                    break;
                case "Quarterly":
                    duration = "3 months";
                    break;
                case "Semi-Annual":
                    duration = "6 months";
                    break;
                case "Annual":
                    duration = "1 year";
                    break;
                case "Premium Annual":
                    duration = "1 year";
                    break;
            }
            
            String fee = "$" + feeField.getText();
            
            tableModel.addRow(new Object[]{
                idField.getText(),
                type,
                fee,
                duration,
                "Active"
            });
            
            JOptionPane.showMessageDialog(this, "Membership plan added successfully!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error adding membership plan!");
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = tblMemberships.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a membership plan to edit!");
        return;
    }
    
    String membershipId = (String) tableModel.getValueAt(selectedRow, 0);
    String currentType = (String) tableModel.getValueAt(selectedRow, 1);
    String currentFee = (String) tableModel.getValueAt(selectedRow, 2);
    currentFee = currentFee.replace("$", "");
    
    String[] types = {"Monthly", "Quarterly", "Semi-Annual", "Annual", "Premium Annual"};
    JComboBox<String> typeCombo = new JComboBox<>(types);
    typeCombo.setSelectedItem(currentType);
    
    JTextField feeField = new JTextField(currentFee);
    
    Object[] message = {
        "Membership Type:", typeCombo,
        "Fee ($):", feeField
    };
    
    int option = JOptionPane.showConfirmDialog(
        this, 
        message, 
        "Edit Membership Plan", 
        JOptionPane.OK_CANCEL_OPTION
    );
    
    if (option == JOptionPane.OK_OPTION) {
        try {
            String type = (String) typeCombo.getSelectedItem();
            String duration = "";
            
            switch (type) {
                case "Monthly":
                    duration = "30 days";
                    break;
                case "Quarterly":
                    duration = "3 months";
                    break;
                case "Semi-Annual":
                    duration = "6 months";
                    break;
                case "Annual":
                    duration = "1 year";
                    break;
                case "Premium Annual":
                    duration = "1 year";
                    break;
            }
            
            String fee = "$" + feeField.getText();
            
            tableModel.setValueAt(type, selectedRow, 1);
            tableModel.setValueAt(fee, selectedRow, 2);
            tableModel.setValueAt(duration, selectedRow, 3);
            
            JOptionPane.showMessageDialog(this, "Membership plan updated successfully!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating membership plan!");
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRow = tblMemberships.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a membership plan to delete!");
        return;
    }
    
    String membershipId = (String) tableModel.getValueAt(selectedRow, 0);
    String type = (String) tableModel.getValueAt(selectedRow, 1);
    
    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this membership plan?\n" + 
        "ID: " + membershipId + "\nType: " + type,
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE
    );
    
    if (confirm == JOptionPane.YES_OPTION) {
        tableModel.removeRow(selectedRow);
        JOptionPane.showMessageDialog(this, "Membership plan deleted successfully!");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        loadMembershipPlans();
        JOptionPane.showMessageDialog(this, "Membership plans refreshed!");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MembershipManagementFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMemberships;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
