/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gym.management.gui;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JTextArea;

/**
 *
 * @author Nomi's
 */
public class PhysicalStatsFrame extends javax.swing.JFrame {
    
    private DefaultTableModel tableModel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PhysicalStatsFrame.class.getName());

    /**
     * Creates new form PhysicalStatsFrame
     */
    public PhysicalStatsFrame() {
        initComponents();
         setupTable();
         loadPhysicalStats();
    }
    
    private void setupTable() {
    tableModel = (DefaultTableModel) tblPhysicalStats.getModel();
}

private void loadPhysicalStats() {
    tableModel.setRowCount(0);
    
    // Sample data - matches database entries
    tableModel.addRow(new Object[]{
        "MEM001", "Alice Johnson", "65.5", "1.70", "22.65", "Healthy", "Good physical condition"
    });
    tableModel.addRow(new Object[]{
        "MEM002", "Bob Smith", "80.0", "1.80", "24.69", "Normal", "Needs to lose weight"
    });
    tableModel.addRow(new Object[]{
        "MEM003", "Charlie Brown", "70.0", "1.75", "22.86", "Healthy", "Recovering from injury"
    });
}

private String getBMIStatus(double bmi) {
    if (bmi < 18.5) {
        return "Underweight";
    } else if (bmi >= 18.5 && bmi < 25) {
        return "Healthy";
    } else if (bmi >= 25 && bmi < 30) {
        return "Overweight";
    } else {
        return "Obese";
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhysicalStats = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Physical Stats Management");

        jPanel1.setBackground(new java.awt.Color(26, 188, 156));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("MEMBER PHYSICAL STATISTICS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(263, 263, 263))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(titleLabel)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblPhysicalStats.setBackground(new java.awt.Color(204, 204, 204));
        tblPhysicalStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Member ID", "Name", "Weight (Kg)", "Height (m)", "BMI", "Status", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPhysicalStats.setRowHeight(25);
        tblPhysicalStats.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblPhysicalStats);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setBackground(new java.awt.Color(46, 204, 113));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Add Stats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(241, 196, 15));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Edit Stats");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(52, 152, 219));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Calculate BMI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(149, 165, 166));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addGap(114, 114, 114)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(100, 100, 100)
                .addComponent(jButton4)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTextField memberIdField = new JTextField();
    JTextField nameField = new JTextField();
    JTextField weightField = new JTextField();
    JTextField heightField = new JTextField();
    JTextArea descArea = new JTextArea(3, 20);
    descArea.setLineWrap(true);
    
    Object[] message = {
        "Member ID:", memberIdField,
        "Name:", nameField,
        "Weight (kg):", weightField,
        "Height (m):", heightField,
        "Description:", new javax.swing.JScrollPane(descArea)
    };
    
    int option = JOptionPane.showConfirmDialog(
        this, 
        message, 
        "Add Physical Stats", 
        JOptionPane.OK_CANCEL_OPTION
    );
    
    if (option == JOptionPane.OK_OPTION) {
        try {
            String memberId = memberIdField.getText();
            String name = nameField.getText();
            double weight = Double.parseDouble(weightField.getText());
            double height = Double.parseDouble(heightField.getText());
            String description = descArea.getText();
            
            // Calculate BMI
            double bmi = weight / (height * height);
            String status = getBMIStatus(bmi);
            
            tableModel.addRow(new Object[]{
                memberId,
                name,
                String.format("%.1f", weight),
                String.format("%.2f", height),
                String.format("%.2f", bmi),
                status,
                description
            });
            
            // Show BMI result
            String result = "Physical stats added successfully!\n\n";
            result += "BMI: " + String.format("%.2f", bmi) + "\n";
            result += "Status: " + status;
            
            JOptionPane.showMessageDialog(this, result);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number format!");
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = tblPhysicalStats.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a member to update stats!");
        return;
    }
    
    String memberId = (String) tableModel.getValueAt(selectedRow, 0);
    String name = (String) tableModel.getValueAt(selectedRow, 1);
    String currentWeight = (String) tableModel.getValueAt(selectedRow, 2);
    String currentHeight = (String) tableModel.getValueAt(selectedRow, 3);
    String currentDesc = (String) tableModel.getValueAt(selectedRow, 6);
    
    JTextField weightField = new JTextField(currentWeight);
    JTextField heightField = new JTextField(currentHeight);
    JTextArea descArea = new JTextArea(currentDesc, 3, 20);
    descArea.setLineWrap(true);
    
    Object[] message = {
        "Member: " + name,
        "Weight (kg):", weightField,
        "Height (m):", heightField,
        "Description:", new javax.swing.JScrollPane(descArea)
    };
    
    int option = JOptionPane.showConfirmDialog(
        this, 
        message, 
        "Update Physical Stats", 
        JOptionPane.OK_CANCEL_OPTION
    );
    
    if (option == JOptionPane.OK_OPTION) {
        try {
            double weight = Double.parseDouble(weightField.getText());
            double height = Double.parseDouble(heightField.getText());
            String description = descArea.getText();
            
            // Calculate new BMI
            double bmi = weight / (height * height);
            String status = getBMIStatus(bmi);
            
            tableModel.setValueAt(String.format("%.1f", weight), selectedRow, 2);
            tableModel.setValueAt(String.format("%.2f", height), selectedRow, 3);
            tableModel.setValueAt(String.format("%.2f", bmi), selectedRow, 4);
            tableModel.setValueAt(status, selectedRow, 5);
            tableModel.setValueAt(description, selectedRow, 6);
            
            String result = "Physical stats updated successfully!\n\n";
            result += "New BMI: " + String.format("%.2f", bmi) + "\n";
            result += "Status: " + status;
            
            JOptionPane.showMessageDialog(this, result);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number format!");
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             JTextField weightField = new JTextField();
    JTextField heightField = new JTextField();
    
    Object[] message = {
        "Enter your weight (kg):", weightField,
        "Enter your height (m):", heightField
    };
    
    int option = JOptionPane.showConfirmDialog(
        this, 
        message, 
        "BMI Calculator", 
        JOptionPane.OK_CANCEL_OPTION
    );
    
    if (option == JOptionPane.OK_OPTION) {
        try {
            double weight = Double.parseDouble(weightField.getText());
            double height = Double.parseDouble(heightField.getText());
            
            double bmi = weight / (height * height);
            String status = getBMIStatus(bmi);
            
            // Create colored result
            String color = "";
            if (bmi < 18.5) {
                color = "orange";
            } else if (bmi >= 18.5 && bmi < 25) {
                color = "green";
            } else if (bmi >= 25 && bmi < 30) {
                color = "orange";
            } else {
                color = "red";
            }
            
            String result = "<html><body style='text-align:center; padding:10px;'>";
            result += "<h2>BMI Calculation Result</h2>";
            result += "<p style='font-size:36px; color:" + color + "; margin:20px;'><b>" + String.format("%.2f", bmi) + "</b></p>";
            result += "<p style='font-size:18px;'>Status: <b>" + status + "</b></p>";
            result += "<hr style='margin:20px 0;'>";
            result += "<h3>BMI Categories:</h3>";
            result += "<table style='margin:auto; text-align:left;'>";
            result += "<tr><td><b>Underweight:</b></td><td>&lt; 18.5</td></tr>";
            result += "<tr><td><b>Healthy Weight:</b></td><td>18.5 - 24.9</td></tr>";
            result += "<tr><td><b>Overweight:</b></td><td>25.0 - 29.9</td></tr>";
            result += "<tr><td><b>Obese:</b></td><td>≥ 30.0</td></tr>";
            result += "</table>";
            result += "</body></html>";
            
            JOptionPane.showMessageDialog(
                this, 
                result, 
                "BMI Calculator Result", 
                JOptionPane.INFORMATION_MESSAGE
            );
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers!");
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         loadPhysicalStats();
         JOptionPane.showMessageDialog(this, "Physical stats refreshed!");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PhysicalStatsFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhysicalStats;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
